apiVersion: v1
kind: Service
metadata:
  name: flask-devops-demo-service
spec:
  type: NodePort
  selector:
    app: flask-devops-demo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
